services:
  - type: web
    name: mealtrack-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mealtrack-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: mealtrack-db
    databaseName: mealtrack
    user: mealtrack
    plan: free
